package ir.maktab127.entity;

public enum OrderStatus {
    WAITING_FOR_PROPOSAL,
    WAITING_FOR_SPECIALIST_SELECTION,
    WAITING_FOR_SPECIALIST_ARRIVAL,
    IN_PROGRESS,
    COMPLETED,
    CANCELLED
}